import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useApp } from '../App';
import { Back, Button, Card, Field, Header, Select } from '../components/UI';

const empty = { nome:'', matricula:'', nascimento:'', escola:'', turma:'', pai:'', mae:'', tamanho:'', status:'Pendente' };
export default function StudentFormPage() {
  const { id } = useParams(); const editing = Boolean(id); const { students, addStudent, updateStudent } = useApp(); const navigate = useNavigate();
  const [form,setForm]=useState(empty); const [errors,setErrors]=useState({});
  useEffect(()=>{ if(editing){const found=students.find(s=>String(s.id)===id); if(found)setForm(found)} },[editing,id,students]);
  const change=(k,v)=>{setForm(f=>({...f,[k]:v}));setErrors(e=>({...e,[k]:''}))};
  const submit=e=>{e.preventDefault(); const next={}; ['nome','matricula','escola','turma'].forEach(k=>{if(!form[k])next[k]='Campo obrigatório'}); if(Object.keys(next).length)return setErrors(next); const idade=form.nascimento?Math.max(0,new Date().getFullYear()-new Date(form.nascimento).getFullYear()):form.idade||'—'; const data={...form,idade}; if(editing)updateStudent(id,data);else addStudent(data); navigate('/alunos');};
  return <div className="page-enter"><Header title={editing?'Editar aluno':'Adicionar aluno'} subtitle={editing?'Atualize os dados cadastrais e a situação do uniforme.':'Cadastre manualmente um novo aluno no sistema.'}/><Back/><form onSubmit={submit}><Card className="p-6 sm:p-8"><Section title="DADOS DO ALUNO"><div className="grid gap-5 md:grid-cols-2"><FormField field="nome" label="Nome completo" required/><FormField field="matricula" label="Matrícula" required/><FormField field="nascimento" label="Data de nascimento" type="date"/></div></Section><Section title="VÍNCULO ESCOLAR"><div className="grid gap-5 md:grid-cols-2"><FormSelect field="escola" label="Escola" required options={['Escola Municipal Central','Escola Municipal Aurora','Escola Municipal do Sol']}/><FormSelect field="turma" label="Turma" required options={['5º A','5º B','6º A','6º B','7º A','7º C','8º A','8º B']}/></div></Section><Section title="RESPONSÁVEIS"><div className="grid gap-5 md:grid-cols-2"><FormField field="pai" label="Nome do pai"/><FormField field="mae" label="Nome da mãe"/></div></Section><Section title="UNIFORME"><div className="grid items-end gap-5 md:grid-cols-[.7fr_.7fr_1.4fr]"><FormSelect field="tamanho" label="Tamanho da camiseta" options={['PP','P','M','G','GG','XGG']}/><FormSelect field="status" label="Situação do uniforme" options={['Pendente','Recebido']}/><p className="pb-3 text-xs text-slate-400">Campos previstos pelas histórias da Sprint para filtro e acompanhamento.</p></div></Section><div className="mt-8 flex justify-end gap-3 border-t border-slate-200 pt-7"><Button variant="secondary" type="button" onClick={()=>navigate('/alunos')}>Cancelar</Button><Button type="submit">{editing?'Salvar alterações':'Cadastrar aluno'}</Button></div></Card></form></div>;
  function FormField({field,label,...props}){return <div><Field label={label} value={form[field]||''} onChange={e=>change(field,e.target.value)} placeholder={`Digite ${label.toLowerCase()}`} {...props}/>{errors[field]&&<p className="mt-1 text-xs text-red-600">{errors[field]}</p>}</div>}
  function FormSelect({field,label,options,...props}){return <div><Select label={label} value={form[field]||''} onChange={e=>change(field,e.target.value)} {...props}><option value="">Selecione</option>{options.map(x=><option key={x}>{x}</option>)}</Select>{errors[field]&&<p className="mt-1 text-xs text-red-600">{errors[field]}</p>}</div>}
}
function Section({title,children}){return <div className="mb-7"><h2 className="mb-3 text-[10px] font-bold text-[#2867ed]">{title}</h2>{children}</div>}
