import { MoreHorizontal, Plus, Upload } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useApp } from '../App';
import { initials } from '../data';
import ImportModal from '../components/ImportModal';
import { Badge, Button, Card, Empty, Header, Select } from '../components/UI';

export default function StudentsPage() {
  const { students, loading, apiStatus } = useApp(); const navigate = useNavigate();
  const [filters, setFilters] = useState({ q: '', turma: '', idade: '', tamanho: '', status: '' }); const [modal, setModal] = useState(false); const [page, setPage] = useState(1);
  const set = (k, v) => { setFilters(f => ({ ...f, [k]: v })); setPage(1); };
  const filtered = useMemo(() => students.filter(s => (!filters.q || `${s.nome} ${s.matricula}`.toLowerCase().includes(filters.q.toLowerCase())) && (!filters.turma || s.turma === filters.turma) && (!filters.idade || String(s.idade) === filters.idade) && (!filters.tamanho || s.tamanho === filters.tamanho) && (!filters.status || s.status === filters.status)), [students, filters]);
  const pages = Math.max(1, Math.ceil(filtered.length / 8)); const rows = filtered.slice((page - 1) * 8, page * 8);
  const options = key => [...new Set(students.map(s => String(s[key])).filter(Boolean))];
  return <div className="page-enter"><Header eyebrow="CADASTRO E CONSULTA" title="Alunos" subtitle="Consulte, filtre, cadastre e acompanhe o recebimento de uniformes." actions={<><Button variant="secondary" onClick={() => setModal(true)}><Upload size={16}/> Importar alunos</Button><Button onClick={() => navigate('/alunos/novo')}><Plus size={16}/> Adicionar aluno</Button></>}/>
    <Card className="mb-6 p-5"><h2 className="text-base font-bold">Pesquisar e filtrar</h2><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-[2.1fr_.75fr_.75fr_.8fr_.8fr]"><label><span className="mb-2 block text-xs font-semibold">Pesquisar</span><input value={filters.q} onChange={e => set('q', e.target.value)} placeholder="Pesquisar por nome ou matrícula..." className="h-11 w-full rounded-lg border border-slate-200 px-4 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"/></label><Filter label="Turma" value={filters.turma} onChange={v => set('turma', v)} options={options('turma')}/><Filter label="Idade" value={filters.idade} onChange={v => set('idade', v)} options={options('idade')}/><Filter label="Tam. camiseta" value={filters.tamanho} onChange={v => set('tamanho', v)} options={options('tamanho')}/><Filter label="Uniforme" value={filters.status} onChange={v => set('status', v)} options={['Recebido','Pendente']}/></div></Card>
    <Card className="overflow-hidden"><div className="px-5 pb-2 pt-5"><h2 className="text-base font-bold">Lista de alunos</h2><p className="text-xs text-slate-500">{students.length} alunos cadastrados · API {apiStatus === 'online' ? 'conectada' : apiStatus === 'offline' ? 'indisponível (modo local)' : 'conectando...'}</p></div><div className="scrollbar-thin overflow-x-auto px-5"><table className="w-full min-w-[850px] border-collapse text-left text-xs"><thead><tr className="bg-slate-50 text-slate-500">{['Aluno','Matrícula','Turma','Idade','Tam.','Uniforme','Ações'].map(h => <th key={h} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{rows.map(s => <tr key={s.id} onDoubleClick={() => navigate(`/alunos/${s.id}`)} className="border-b border-slate-100 hover:bg-slate-50"><td className="px-4 py-3"><button onClick={() => navigate(`/alunos/${s.id}`)} className="flex items-center gap-3 font-semibold"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-blue-50 text-[10px] font-medium text-blue-600">{initials(s.nome)}</span>{s.nome}</button></td><td className="px-4 py-3">{s.matricula}</td><td className="px-4 py-3">{s.turma}</td><td className="px-4 py-3">{s.idade} anos</td><td className="px-4 py-3 font-semibold">{s.tamanho}</td><td className="px-4 py-3"><Badge status={s.status}/></td><td className="px-4 py-3"><button aria-label="Editar aluno" onClick={() => navigate(`/alunos/${s.id}/editar`)} className="flex h-9 w-12 items-center justify-center rounded-lg border border-slate-200 bg-slate-50 hover:bg-slate-100"><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table>{!loading && !rows.length && <Empty text="Nenhum aluno encontrado com esses filtros."/>}{loading && <div className="py-20 text-center text-sm text-slate-400">Carregando alunos...</div>}</div><div className="flex items-center justify-between gap-4 px-9 py-5 text-xs text-slate-500"><span>Mostrando {filtered.length ? (page-1)*8+1 : 0}–{Math.min(page*8, filtered.length)} de {filtered.length} alunos</span><div className="flex gap-2"><button disabled={page===1} onClick={() => setPage(p=>p-1)} className="h-10 w-10 rounded-lg border border-slate-200 disabled:opacity-40">‹</button>{Array.from({length: pages},(_,i)=>i+1).slice(0,3).map(p=><button key={p} onClick={()=>setPage(p)} className={`h-10 w-10 rounded-lg border ${page===p?'border-blue-600 bg-blue-600 text-white':'border-slate-200 bg-white'}`}>{p}</button>)}<button disabled={page===pages} onClick={() => setPage(p=>p+1)} className="h-10 w-10 rounded-lg border border-slate-200 disabled:opacity-40">›</button></div></div></Card>{modal && <ImportModal close={() => setModal(false)}/>}</div>;
}
function Filter({ label, value, onChange, options }) { return <Select label={label} value={value} onChange={e=>onChange(e.target.value)}><option value="">Todas</option>{options.map(x=><option key={x}>{x}</option>)}</Select>; }
