import { Edit3, PackageCheck, X } from 'lucide-react';
import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useApp } from '../App';
import { dateBR, initials } from '../data';
import { Back, Badge, Button, Card, Empty, Header, Field } from '../components/UI';

export default function StudentDetailsPage(){
  const {id}=useParams(); const navigate=useNavigate(); const {students,deliveries,addDelivery}=useApp(); const [modal,setModal]=useState(false); const s=students.find(x=>String(x.id)===id); const list=deliveries[id]||[];
  if(!s)return <div><Back/><Empty text="Aluno não encontrado."/></div>;
  const last=list[0];
  return <div className="page-enter"><Header title={s.nome} subtitle={`${s.turma} · Matrícula ${s.matricula}`} actions={<><Button variant="secondary" onClick={()=>navigate(`/alunos/${id}/editar`)}><Edit3 size={16}/>Editar aluno</Button><Button onClick={()=>setModal(true)}><PackageCheck size={16}/>Registrar entrega</Button></>}/><Back/><div className="grid gap-5 lg:grid-cols-2"><Card className="p-6"><h2 className="text-base font-bold">Dados do aluno</h2><div className="my-4 flex h-16 w-16 items-center justify-center rounded-full bg-blue-50 text-lg font-medium text-blue-600">{initials(s.nome)}</div><div className="grid grid-cols-2 gap-x-8 gap-y-5 text-xs"><Info label="Matrícula" value={s.matricula}/><Info label="Nascimento" value={dateBR(s.nascimento)}/><Info label="Escola" value={s.escola}/><Info label="Turma" value={s.turma}/><Info label="Pai" value={s.pai||'—'}/><Info label="Mãe" value={s.mae||'—'}/></div></Card><Card className="p-6"><h2 className="text-base font-bold">Uniforme</h2><p className="mb-1 text-xs text-slate-400">Situação atual do aluno</p><Badge status={s.status}/><div className="mt-6 grid grid-cols-2 gap-7"><Info label="Tamanho da camiseta" value={s.tamanho}/><Info label="Uniformes recebidos" value={s.recebidos}/><Info label="Última entrega" value={last?dateBR(last.data):'—'}/><Info label="Peças na última entrega" value={last?`${last.pecas} peças`:'—'}/></div></Card></div><Card className="mt-5 min-h-[340px] overflow-hidden"><div className="px-6 pb-2 pt-5"><h2 className="text-base font-bold">Histórico de entregas</h2><p className="text-xs text-slate-400">Entregas registradas para este aluno</p></div>{list.length?<div className="scrollbar-thin overflow-x-auto px-6"><table className="w-full min-w-[650px] text-left text-xs"><thead><tr className="bg-slate-50 text-slate-500">{['Data','Responsável','Peças','Detalhes'].map(x=><th key={x} className="px-4 py-3 font-medium">{x}</th>)}</tr></thead><tbody>{list.map(x=><tr key={x.id} className="border-b border-slate-100"><td className="px-4 py-5 font-semibold">{dateBR(x.data)}</td><td className="px-4 py-5">{x.responsavel}</td><td className="px-4 py-5">{x.pecas} {x.pecas===1?'peça':'peças'}</td><td className="px-4 py-5 text-slate-500">{x.detalhes}</td></tr>)}</tbody></table></div>:<Empty text="Nenhuma entrega registrada para este aluno."/>}</Card>{modal&&<DeliveryModal id={id} close={()=>setModal(false)} save={addDelivery}/>}</div>;
}
function Info({label,value}){return <div><div className="mb-1 text-[10px] font-medium text-slate-500">{label}</div><div className="font-semibold text-slate-900">{value}</div></div>}
function DeliveryModal({id,close,save}){const [form,setForm]=useState({data:new Date().toISOString().slice(0,10),responsavel:'',pecas:1,detalhes:''});const submit=e=>{e.preventDefault();save(id,{...form,id:Date.now(),pecas:Number(form.pecas)});close()};return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-5"><form onSubmit={submit} className="relative w-full max-w-lg rounded-2xl bg-white p-8 shadow-2xl"><button type="button" onClick={close} className="absolute right-5 top-5 text-slate-400"><X/></button><h2 className="mb-6 text-xl font-bold">Registrar entrega</h2><div className="grid gap-5 sm:grid-cols-2"><Field label="Data" type="date" required value={form.data} onChange={e=>setForm({...form,data:e.target.value})}/><Field label="Quantidade de peças" type="number" min="1" required value={form.pecas} onChange={e=>setForm({...form,pecas:e.target.value})}/><Field label="Responsável" required value={form.responsavel} onChange={e=>setForm({...form,responsavel:e.target.value})} className="sm:col-span-2"/><Field label="Detalhes das peças" required value={form.detalhes} onChange={e=>setForm({...form,detalhes:e.target.value})} className="sm:col-span-2"/></div><div className="mt-7 flex justify-end gap-3 border-t border-slate-200 pt-6"><Button type="button" variant="secondary" onClick={close}>Cancelar</Button><Button type="submit">Registrar entrega</Button></div><p className="mt-4 text-xs text-slate-400">A API publicada registra entrada de estoque, não entrega a aluno. Este registro fica salvo localmente.</p></form></div>}
