import { FileUp, X } from 'lucide-react';
import { useRef, useState } from 'react';
import { useApp } from '../App';
import { Button } from './UI';

export default function ImportModal({ close }) {
  const { importStudents } = useApp(); const input = useRef(); const [file, setFile] = useState(null); const [error, setError] = useState('');
  const choose = f => { if (f && !/\.(csv|json)$/i.test(f.name)) setError('Selecione um arquivo CSV ou JSON.'); else { setError(''); setFile(f); } };
  const submit = async () => { if (!file) return setError('Selecione um arquivo para importar.'); try { const text = await file.text(); let rows; if (/\.json$/i.test(file.name)) rows = JSON.parse(text); else { const [head,...lines] = text.trim().split(/\r?\n/); const keys=head.split(/[,;]/).map(x=>x.trim()); rows=lines.map(line=>Object.fromEntries(line.split(/[,;]/).map((v,i)=>[keys[i],v.trim()]))); } if(!Array.isArray(rows)) throw new Error(); importStudents(rows); close(); } catch { setError('Não foi possível ler o arquivo. Verifique o formato.'); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-5"><div className="page-enter relative w-full max-w-[610px] rounded-2xl bg-white p-8 shadow-2xl sm:p-10"><button onClick={close} className="absolute right-6 top-6 text-slate-400 hover:text-slate-700"><X size={20}/></button><h2 className="text-2xl font-bold">Importar alunos</h2><p className="mt-1 text-sm text-slate-500">Envie um arquivo com os alunos para cadastro em lote.</p><div onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0])}} className="mt-8 flex min-h-48 flex-col items-center justify-center rounded-xl border border-dashed border-slate-300 bg-slate-50 text-center"><FileUp className="mb-3 text-[#2867ed]" size={32}/><b className="text-sm">{file ? file.name : 'Arraste o arquivo aqui'}</b><span className="mt-1 text-xs text-slate-400">Formato CSV ou JSON</span><input ref={input} type="file" accept=".csv,.json" hidden onChange={e=>choose(e.target.files[0])}/><Button variant="secondary" onClick={()=>input.current.click()} className="mt-5 h-10">Selecionar arquivo</Button></div>{error&&<p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-8 flex justify-end gap-3 border-t border-slate-200 pt-6"><Button variant="secondary" onClick={close}>Cancelar</Button><Button onClick={submit}>Importar</Button></div><p className="mt-5 text-xs text-slate-400">O backend ainda não fornece endpoint de importação; os dados ficam salvos localmente neste navegador.</p></div></div>;
}
